# Generated by Django 4.1.3 on 2022-11-27 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Documento')),
                ('fecha_registro', models.DateField(default=datetime.datetime(2022, 11, 26, 19, 27, 21, 146431), verbose_name='Fecha de Registro')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('Fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('celular', models.PositiveIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='avatar/%y/%m/%d')),
                ('documentos', models.FileField(blank=True, null=True, upload_to='cvitae/%y/%m/%d')),
            ],
        ),
    ]
